// <auto-generated />
namespace MusteriYonetimSistemi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Init_2_for_Payments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Init_2_for_Payments));
        
        string IMigrationMetadata.Id
        {
            get { return "202403121211539_Init_2_for_Payments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
